controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    
    xarm6_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

xarm6_velocity_controller:
  ros__parameters:
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    joints:
      - xarm6_joint1
      - xarm6_joint2
      - xarm6_joint3
      - xarm6_joint4
      - xarm6_joint5
      - xarm6_joint6
    # Velocity limits (rad/s)
    max_velocity: 0.2 #3.14
    min_velocity: -0.2 #-3.14
    # Controller gains （Not used in velocity controller）
    kp: 1.0
    kd: 0.1
    # Safety parameters
    timeout: 0.5
    allow_partial_joints_goal: true
