controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    traj_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    # Original comment: only for fake control (?)
    gripper_traj_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Original comment: only for fake control (?)
    bio_gripper_traj_controller:
      type: joint_trajectory_controller/JointTrajectoryController

traj_controller:
  ros__parameters:
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.0
      joint1: {trajectory: 1.0, goal: 0.01}
      joint2: {trajectory: 1.0, goal: 0.01}
      joint3: {trajectory: 1.0, goal: 0.01}
      joint4: {trajectory: 1.0, goal: 0.01}
      joint5: {trajectory: 1.0, goal: 0.01}
    interface_name: position
    state_publish_rate: 25.0
    action_monitor_rate: 10.0
    update_rate: 25

# Original comment: only for fake control (?)
gripper_traj_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - drive_joint
    interface_name: position

# only for fake control
bio_gripper_traj_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      # - left_finger_joint
      - right_finger_joint
    interface_name: position
