controller_names:
  - xarm6_traj_controller

xarm6_traj_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - xarm6_joint1
    - xarm6_joint2
    - xarm6_joint3
    - xarm6_joint4
    - xarm6_joint5
    - xarm6_joint6
